quote_of_the_day_api_call:
  default: ''
  description:
    en: "Full API call including address (without any querystring)"
quote_of_the_day_api_querystring:
  default: ''
  description:
    en: "Querystring parameters sent to quote API"
